version: "3"
services:
  jenkins:
    image: jenkins/jenkins:2.471-jdk21
    volumes:
      - C:\docker\jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
    links:
      - worker-1

  worker-1:
    image: jenkins/ssh-agent:latest-jdk21
    volumes:
      - C:\docker\jenkins_worker:/home/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFiWSW/tFnij6IHBI977sauf+KX5uilNx0Em6zBA51aKAZN2a9ylzRCCQkWctKHv2IJKuQZy3YWpFzMXmP0964J8FPsVkzdnjzXT9epgpalsfLK8Yq8oysz1qQS+Vu01LoJ8gzeMziIZrH48O0Hza5L7mGbid0QehDdZj9siY7jfYh1pdqyAIod5B584x2dcFYrSxkO5+py3k2+Y1I41JjCGLdyujN83S8z8H8R0BgVRI3CS++QsSrwBvgzd2VFIVf6nmWGG2g67Q9aRlD4tMrJtZIC2Dqd/neCmX5Yd9xGPMIVd2SdMqgURnbv2h7aqo7+JCYJSiKN+xjZNsueLProQARakhWJ0d2EubpG5uGszSku3FN2K0FKZiuWbdCz1ysyPIqsvmZ0RPL7ufXDaOFygYkKQPdTwFC9XIml2nxsKrCdEkHzQaEE64Rk1e31ywp/ohUf7hvpD9E7zAjI5iPnR082iox9gVCFGvL9KZdmQ6BHz9ezm1ZGaBVBCTDWt0=
#  sonarqube:
#    image: sonarqube:9-community
#    ports:
#      - "9000:9000"