name: cicd
on:
  workflow_dispatch:
    inputs:
      tags: # ex) v1.0.0 을 매개변수로 받음
        description: 'Set Tags Name'
        required: true
        default: master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release: ${{steps.set-version.outputs.VERSION_NAME}}
    steps:
      - id: set-version #변수명 사용위해 name 말고 id 사용
        run: |
          echo "VERSION_NAME=$(echo "${{github.event.inputs.tags}}" | sed"s/\./\-/g")" >> $GITHUB_OUTPUT
      - name: Debug Input Tags
        run: |
          echo "Input Tags: ${{ github.event.inputs.tags }}"
      - name : Check Version Name
        run: |
          echo "Check Version -> ${{steps.set-version.outputs.VERSION_NAME}}"


      - name: Checkout Source Code #위에서 받은 tag 파라미터 사용
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.tags }}'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup JDK 21 #JDK설치
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Gradlew
        run: ./gradlew clean test bootJar #clean, test, bootJar 실행

      - name: Add version #bootJar로 build/libs에 생성된 jar파일 이름 변경
        run: |
          mv build/libs/cicd-study-0.0.1-SNAPSHOT.jar build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-study-application #cicd-study-application.zip으로 생성됨
          path: build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar